choices_prompt: "Enter the name of the item: (%{choices})"
invalid_prompt: "Invalid item. Please enter one of the valid items: %{choices}"
item_added_message: "%{item} added to the cash register."
current_items_message: "Current items: %{items}"
menu_header: "Menu:"
add_item_option: "1. Add Item"
show_total_option: "2. Show Total"
quit_option: "3. Quit"
total_message: "The total is %{total}"
exit_message: "Exiting the cash register. Thank you!"
invalid_choice_message: "Invalid choice. Please choose a valid option."
menu_choice_prompt: "Enter your choice (1-3): "
